# Generated by Django 3.2.25 on 2024-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amodel',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
            preserve_default=False,
        ),
    ]
